### ISSUE TITLE
Hide Distractions Toggle?

### ISSUE THREAD

**Issue by DoctorG** [davekeck/Xcode-4-Fixins#12]
How about if if the HideDistractions hot key toggled between hidden/standard view.   How do you get back to "distracted state" easily?

Thanks for these great tweaks!

**Comment by hlfcoding** [comment]
I was surprised this wasn't already included. Definitely a must-have. Otherwise definitely a huge improvement.

**Comment by vtagle** [comment]
I just ran into this too. It looks like Hide Distractions works by toggling off the Navigator view and the toolbar so to get back to the distracted state, go to the View menu and Show Toolbar and Show Navigator (under the Navigators sub-menu).

**Comment by tom-seddon** [comment]
Closed by issue #13.

--Tom
