### ISSUE TITLE
FindFix request: prefill search field with text at caret

### ISSUE THREAD

**Issue by mike-lischke** [davekeck/Xcode-4-Fixins#17]
Please add auto population of the search field with the current word at the caret (if there's any), just like Visual Studio does. This avoids this annoying select->copy->find->paste sequence. Thank you.

**Comment by hsarret** [comment]
+1

**Comment by tom-seddon** [comment]
Fixed - after installing the latest FindFix fixin activate Find -> Auto Populate Find Bar (Xcode 5) or Edit -> Find -> Auto Populate Find Bar (Xcode 4).

--Tom
