### ISSUE TITLE
Update build script with Xcode5GM UUID

### ISSUE THREAD

**Issue by mralexgray** [davekeck/Xcode-4-Fixins#25]

**Comment by jdelStrother** [comment]
:heart:

Is it worth mentioning in the readme that for this to work, you need to build the "Build All Fixins" target?  The readme currently makes it sound like you can just build the plugin you're interested in.

**Comment by tom-seddon** [comment]
I think this is fixed now.

--Tom

**Comment by tom-seddon** [comment]
While I was there I added a note about building for Xcode 5.

--Tom
