### ISSUE TITLE
Deleted workspace

### ISSUE THREAD

**Issue by davekeck** [davekeck/Xcode-4-Fixins#5]
Hey guys, as the project grows I think the workspace approach to installing the plugins makes less and less sense, so I just deleted the workspace and moved the plugin directories into the root directory. My reasoning is that once we have > 10 plugins, Xcode's behavior will change significantly after installing the entire plugin collection which might not be what users want. Let me know if you all disagree and we can bring the workspace back.

**Comment by davekeck** [comment]
Nevermind, opening a bunch of project files is tedious, so I brought back the workspace but eliminated the build-all-projects scheme. So now to install the fixins you want, you open the workspace, change the scheme to the fixin you want to install, and build. I think that's the best of both worlds -- let me know what you all think.

**Comment by tom-seddon** [comment]
Yep, I like the new arrangement! Everything in one place, but still easy to compile only the parts you want.

--Tom
