### ISSUE TITLE
Mountain Lion and Xcode 4.4

### ISSUE THREAD

**Issue by Kamek** [davekeck/Xcode-4-Fixins#7]
The Current Line Highlighter plugin doesn't seem to work for me on ML with Xcode 4.4. Anyone else have this problem?

**Comment by andyarvanitis** [comment]
It's working ok for me. Is this the first time you're using it on a fresh install? By default, there is no highlight color, so you'll have to choose one to start in order to see anything. You also need to start off with a source code window to even see the color selection menu item.

**Comment by Kamek** [comment]
Where do I choose the highlight color? I'd assumed it would be my selected color by default.

**Comment by Kamek** [comment]
Sorry my bad, these work just fine. I found the current line settings. I'd like to say thanks for the awesome plugins. The user scripts are especially interesting, hopefully they catch on. Keep up the good work!

**Comment by andyarvanitis** [comment]
Ok, great! Glad you're enjoying them. Closing issue then.
