### ISSUE TITLE
Cannot "Hide Distraactions" etc view "Key Bindings"

### ISSUE THREAD

**Issue by mralexgray** [davekeck/Xcode-4-Fixins#9]
See title.

Xcode limitation?  Workaround?

Is this cause the API is closed or because its all "a-swizzle"?

**Comment by tom-seddon** [comment]
Xcode seems to have its own list of commands, which it uses to fill the key bindings window...

As a workaround, you can use System Preferences, Keyboard pane, Keyboard Shortcuts section to set up a keyboard shortcut for Hide Distractions (and probably any others that have menu items). Select Application Shortcuts in the left-hand list, then click the + button to add a shortcut for use in Xcode.app.

**Comment by tom-seddon** [comment]
Will close in the next week if there are no further comments.

**Comment by davekeck** [comment]
Just now seeing this, so for folks in the future:

The Hide Distractions key combination isn't editable within Xcode's UI (adding that feature would've taken a lot more work...). You can however edit the key combination at the top of XCFixin_HideDistractions.m via the 'kHideDistractionsKey' and 'kHideDistractionsKeyModifiers' constants. Just recompile & relaunch, and you should be good.

Note however if Xcode already has a command bound to whatever key combination you pick, it may not work -- you need to free up whatever key combination you want first.
